### ISSUE TITLE
@_INTERRUPT_NAME_@ = unknown_interrupt (armvX-m.S.tmplt)

### ISSUE THREAD

**Issue by kevlar700** [AdaCore/startup-gen#40]
The svd2ada code using --gen-interrupts creates a handler.S with comments matching the correct interrupt names and numbers. However crt0.s labels them as __unknown_interrupt_handler. Before I dig into the code. Should they currently be unknown and if so. Is it worth me looking into a PR bringing code from svd2ada to implement the names?

**Comment by Fabien-Chouteau** [comment]
Hi @kevlar700, `startup-gen` provides a way to specify the name of an interrupt handler with:
```ada
for Interrupt("<ID>") use "<NAME>";
```
